version: '3.8'

services:
  gmail-monitor:
    image: gmail-telegram-monitor:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - gmail-network
    secrets:
      - gmail_env
      - gmail_credentials
    configs:
      - source: gmail_token
        target: /app/token.json
    environment:
      - TZ=America/Sao_Paulo
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      labels:
        - "app=gmail-monitor"
        - "version=1.0"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  gmail-network:
    driver: overlay

secrets:
  gmail_env:
    file: ./.env
  gmail_credentials:
    file: ./credentials.json

configs:
  gmail_token:
    file: ./token.json
